name: CI
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-16.04
    
    strategy:
      matrix:
        node-version: [11.x, 12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Rodar os testes 
        run: npm run test
        
      - name: Iniciar serviço
        run: npm run dev:server & npx wait-on http://localhost:3000/api/accounts
